# Generated by Django 3.2.8 on 2021-10-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
